spring:
  datasource:
    url: ${url}
    username:  ${user}
    password: ${password}
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: validate
  config:
    import: keys.properties

server:
  port: ${port}
