spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username:  ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: validate
  config:
    import: keys.properties

server:
  port: ${port}
